name: MoreArrows
version: ${project.version}
main: me.orangemonkey68.morearrowspaper.MoreArrows
api-version: "1.15.1"
authors: [Orangemonkey68]
description: Adds more arrow types to minecraft
commands:
  explosivearrow:
    usage: explosivearrow [number]
permissions:
  morearrows.debug:
    description: Sends players debug logs
    default: false

